package com.pckeyboard.ime.view

/**
 * Searchable emoji keyword list. English-only for now (works regardless of
 * the user's active keyboard locale because the search query is just
 * lowercase text), but the data structure is locale-keyed so HU / DE / ES
 * keyword sets can be folded in later without changing the search API.
 */
object EmojiKeywords {

    /** Returns every emoji whose keyword list contains a token that
     *  starts with the (lowercased) query. */
    fun search(query: String): List<String> {
        val q = query.trim().lowercase()
        if (q.isEmpty()) return emptyList()
        val out = LinkedHashSet<String>()
        for ((emoji, kws) in DATA) {
            if (kws.any { it.startsWith(q) }) out.add(emoji)
        }
        return out.toList()
    }

    /** emoji → list of search tokens (all lowercase). */
    private val DATA: Map<String, List<String>> = linkedMapOf(
        // Smileys
        "😀" to listOf("grinning", "face", "smile", "happy"),
        "😃" to listOf("smile", "happy", "face", "joy", "grin"),
        "😄" to listOf("smile", "grin", "happy", "joy"),
        "😁" to listOf("beaming", "smile", "happy", "grin"),
        "😆" to listOf("laugh", "smile", "happy", "lol"),
        "😅" to listOf("sweat", "smile", "relief", "happy", "phew"),
        "🤣" to listOf("rofl", "laugh", "rolling", "floor"),
        "😂" to listOf("joy", "happy", "tears", "laugh", "lol"),
        "🙂" to listOf("smile", "slight", "happy"),
        "🙃" to listOf("upside", "down", "silly"),
        "😉" to listOf("wink", "smile", "flirt"),
        "😊" to listOf("blush", "smile", "happy", "content"),
        "😇" to listOf("angel", "halo", "innocent"),
        "🥰" to listOf("love", "hearts", "smile", "happy"),
        "😍" to listOf("love", "heart", "eyes", "smile"),
        "🤩" to listOf("star", "struck", "wow"),
        "😘" to listOf("kiss", "love", "smile"),
        "😗" to listOf("kiss", "whistle"),
        "😚" to listOf("kiss", "closed", "eyes"),
        "🥲" to listOf("tear", "smile", "bittersweet"),
        "😋" to listOf("yum", "tongue", "tasty"),
        "😛" to listOf("tongue", "playful"),
        "😜" to listOf("wink", "tongue", "playful"),
        "🤪" to listOf("zany", "crazy", "wild"),
        "🤑" to listOf("money", "rich", "cash"),
        "🤗" to listOf("hug", "smile"),
        "🤭" to listOf("oops", "giggle", "shy"),
        "🤫" to listOf("shush", "quiet", "secret"),
        "🤔" to listOf("think", "hmm", "wonder"),
        "🤐" to listOf("zip", "mouth", "silent"),
        "🤨" to listOf("eyebrow", "skeptical", "suspicious"),
        "😐" to listOf("neutral", "meh"),
        "😑" to listOf("expressionless", "blank"),
        "😶" to listOf("speechless", "blank", "no", "mouth"),
        "😏" to listOf("smirk", "smug"),
        "😒" to listOf("unamused", "meh", "annoyed"),
        "🙄" to listOf("roll", "eyes", "annoyed"),
        "😬" to listOf("grimace", "awkward"),
        "😌" to listOf("relieved"),
        "😔" to listOf("pensive", "sad"),
        "😪" to listOf("sleepy", "tired"),
        "🤤" to listOf("drool", "yummy"),
        "😴" to listOf("sleep", "tired", "sleeping", "zzz"),
        "😷" to listOf("mask", "sick"),
        "🤒" to listOf("sick", "ill", "thermometer"),
        "🤕" to listOf("hurt", "bandage", "injured"),
        "🤢" to listOf("sick", "nausea", "gross"),
        "🤮" to listOf("vomit", "sick", "gross"),
        "🤧" to listOf("sneeze", "sick", "cold"),
        "🥵" to listOf("hot", "sweat", "heat"),
        "🥶" to listOf("cold", "freezing"),
        "😎" to listOf("cool", "sunglasses"),
        "🤓" to listOf("nerd", "geek", "glasses"),
        "🧐" to listOf("monocle", "fancy"),
        "🥳" to listOf("party", "celebrate", "birthday"),
        "🥺" to listOf("pleading", "puppy", "cute"),
        "😢" to listOf("cry", "sad", "tear"),
        "😭" to listOf("sob", "cry", "sad"),
        "😱" to listOf("scream", "fear", "shocked"),
        "😡" to listOf("angry", "mad", "rage"),
        "😠" to listOf("angry", "mad"),
        "🤬" to listOf("swear", "curse", "angry"),

        // Hands
        "👍" to listOf("thumbs", "up", "like", "ok", "yes"),
        "👎" to listOf("thumbs", "down", "dislike", "no"),
        "👌" to listOf("ok", "perfect"),
        "✌️" to listOf("peace", "victory"),
        "🤞" to listOf("crossed", "fingers", "luck", "hope"),
        "🤟" to listOf("love", "you", "rock"),
        "🤘" to listOf("rock", "horns"),
        "🤙" to listOf("call", "me", "shaka"),
        "👋" to listOf("wave", "hi", "hello", "bye"),
        "🙏" to listOf("pray", "thanks", "please"),
        "🙌" to listOf("raised", "hands", "praise"),
        "👏" to listOf("clap", "applause", "bravo"),
        "💪" to listOf("muscle", "strong", "flex"),
        "🤝" to listOf("handshake", "deal", "agree"),

        // Hearts and symbols
        "❤️" to listOf("heart", "love", "red"),
        "🧡" to listOf("heart", "orange"),
        "💛" to listOf("heart", "yellow"),
        "💚" to listOf("heart", "green"),
        "💙" to listOf("heart", "blue"),
        "💜" to listOf("heart", "purple"),
        "🖤" to listOf("heart", "black"),
        "🤍" to listOf("heart", "white"),
        "💔" to listOf("broken", "heart", "sad"),
        "💕" to listOf("hearts", "love"),
        "💖" to listOf("sparkling", "heart", "love"),
        "💯" to listOf("100", "hundred", "perfect", "score"),
        "💢" to listOf("anger"),
        "💥" to listOf("boom", "explosion", "collision"),
        "💫" to listOf("dizzy", "stars"),
        "💦" to listOf("sweat", "drops"),
        "💨" to listOf("dash", "wind", "fast"),
        "💤" to listOf("zzz", "sleep"),

        // Common objects + nature
        "🔥" to listOf("fire", "hot", "lit", "flame"),
        "✨" to listOf("sparkles", "shine"),
        "⭐" to listOf("star"),
        "🌟" to listOf("star", "glow", "sparkle"),
        "☀️" to listOf("sun", "sunny", "weather"),
        "🌙" to listOf("moon", "night"),
        "🌈" to listOf("rainbow", "pride"),
        "☁️" to listOf("cloud", "weather"),
        "❄️" to listOf("snow", "cold", "snowflake"),
        "⚡" to listOf("lightning", "bolt", "fast", "zap"),
        "🎉" to listOf("party", "tada", "celebrate"),
        "🎊" to listOf("confetti", "party", "celebrate"),
        "🎁" to listOf("gift", "present", "wrapped"),
        "🎂" to listOf("cake", "birthday"),
        "🍰" to listOf("cake", "slice", "dessert"),
        "🍕" to listOf("pizza", "food"),
        "🍔" to listOf("burger", "food"),
        "🍟" to listOf("fries", "chips", "food"),
        "🌮" to listOf("taco", "food"),
        "🍣" to listOf("sushi", "food"),
        "🍺" to listOf("beer", "drink"),
        "🍷" to listOf("wine", "drink"),
        "☕" to listOf("coffee", "drink", "hot"),
        "🍵" to listOf("tea", "drink"),
        "🥛" to listOf("milk", "drink"),
        "🍎" to listOf("apple", "fruit"),
        "🍌" to listOf("banana", "fruit"),
        "🍓" to listOf("strawberry", "fruit"),

        // Animals
        "🐶" to listOf("dog", "puppy"),
        "🐱" to listOf("cat", "kitten"),
        "🐰" to listOf("rabbit", "bunny"),
        "🦊" to listOf("fox"),
        "🐻" to listOf("bear"),
        "🐼" to listOf("panda"),
        "🐨" to listOf("koala"),
        "🦁" to listOf("lion"),
        "🐯" to listOf("tiger"),
        "🐮" to listOf("cow"),
        "🐷" to listOf("pig"),
        "🐸" to listOf("frog"),
        "🐵" to listOf("monkey"),
        "🐔" to listOf("chicken"),
        "🐧" to listOf("penguin"),
        "🐦" to listOf("bird"),
        "🦆" to listOf("duck"),
        "🐺" to listOf("wolf"),
        "🦄" to listOf("unicorn"),
        "🐝" to listOf("bee"),
        "🦋" to listOf("butterfly"),
        "🐢" to listOf("turtle"),
        "🐍" to listOf("snake"),
        "🐙" to listOf("octopus"),
        "🦀" to listOf("crab"),
        "🐠" to listOf("fish"),
        "🐳" to listOf("whale"),
        "🦈" to listOf("shark"),

        // Activities + transport
        "⚽" to listOf("soccer", "football", "ball"),
        "🏀" to listOf("basketball", "ball"),
        "🏈" to listOf("football", "ball"),
        "⚾" to listOf("baseball", "ball"),
        "🎾" to listOf("tennis", "ball"),
        "🏐" to listOf("volleyball", "ball"),
        "🎱" to listOf("pool", "billiards"),
        "🎲" to listOf("dice", "game"),
        "🎮" to listOf("game", "controller", "video"),
        "🎤" to listOf("microphone", "mic", "sing"),
        "🎧" to listOf("headphones", "music"),
        "🎵" to listOf("music", "note"),
        "🎶" to listOf("music", "notes"),
        "🚗" to listOf("car"),
        "🚕" to listOf("taxi"),
        "🚌" to listOf("bus"),
        "🚓" to listOf("police", "car"),
        "🚑" to listOf("ambulance"),
        "🚒" to listOf("fire", "truck"),
        "🚲" to listOf("bicycle", "bike"),
        "✈️" to listOf("plane", "airplane"),
        "🚀" to listOf("rocket", "space"),
        "🚁" to listOf("helicopter"),
        "🚢" to listOf("ship", "boat"),
        "🏠" to listOf("house", "home"),

        // Symbols + flags-like
        "✅" to listOf("check", "ok", "yes", "tick"),
        "❌" to listOf("x", "no", "wrong", "cross"),
        "❓" to listOf("question", "mark"),
        "❗" to listOf("exclamation", "mark"),
        "⚠️" to listOf("warning"),
        "🚫" to listOf("no", "forbidden", "prohibited"),
        "♻️" to listOf("recycle", "green"),
        "💡" to listOf("idea", "bulb", "light"),
        "🔔" to listOf("bell", "notification"),
        "🔇" to listOf("mute", "silent", "no", "sound"),
        "🔊" to listOf("speaker", "loud", "sound"),
        "📱" to listOf("phone", "mobile", "smartphone"),
        "💻" to listOf("laptop", "computer"),
        "⌚" to listOf("watch", "time"),
        "📷" to listOf("camera", "photo"),
        "🎥" to listOf("camera", "movie", "video"),
        "📺" to listOf("tv", "television"),
        "🔑" to listOf("key", "lock"),
        "🔒" to listOf("lock", "secure", "locked"),
        "🔓" to listOf("unlock", "unlocked"),
        "💰" to listOf("money", "bag", "cash"),
        "💳" to listOf("credit", "card"),
        "📚" to listOf("books", "study"),
        "✏️" to listOf("pencil", "write"),
        "✒️" to listOf("pen", "write"),
        "📝" to listOf("memo", "note", "write"),
        "📅" to listOf("calendar", "date"),
        "⏰" to listOf("clock", "alarm", "time"),
        "⏳" to listOf("hourglass", "time", "waiting")
    )
}
