package com.pckeyboard.ime.view

/**
 * Searchable emoji keyword list. English-only for now (the search query
 * lowercases regardless of the user's active keyboard locale), but the
 * data structure is open for HU / DE / ES keyword sets to be folded in
 * later without changing the search API.
 *
 * Every emoji shipped in [EmojiCatalog] is registered here with at least
 * one keyword so the picker's "search the full keyboard" mode can find
 * any catalogue entry — plus a long tail of frequently-searched flags,
 * gestures, professions, body parts and household objects.
 */
object EmojiKeywords {

    /** Returns every emoji whose keyword list contains a token that
     *  starts with the (lowercased) query. */
    fun search(query: String): List<String> {
        val q = query.trim().lowercase()
        if (q.isEmpty()) return emptyList()
        val out = LinkedHashSet<String>()
        for ((emoji, kws) in DATA) {
            if (kws.any { it.startsWith(q) }) out.add(emoji)
        }
        return out.toList()
    }

    /** emoji → list of search tokens (all lowercase). */
    private val DATA: Map<String, List<String>> = linkedMapOf(
        // ---------------- Smileys & emotion ----------------
        "😀" to listOf("grinning", "face", "smile", "happy"),
        "😃" to listOf("smile", "happy", "face", "joy", "grin"),
        "😄" to listOf("smile", "grin", "happy", "joy"),
        "😁" to listOf("beaming", "smile", "happy", "grin"),
        "😆" to listOf("laugh", "smile", "happy", "lol"),
        "😅" to listOf("sweat", "smile", "relief", "happy", "phew"),
        "🤣" to listOf("rofl", "laugh", "rolling", "floor"),
        "😂" to listOf("joy", "happy", "tears", "laugh", "lol"),
        "🙂" to listOf("smile", "slight", "happy"),
        "🙃" to listOf("upside", "down", "silly"),
        "😉" to listOf("wink", "smile", "flirt"),
        "😊" to listOf("blush", "smile", "happy", "content"),
        "😇" to listOf("angel", "halo", "innocent"),
        "🥰" to listOf("love", "hearts", "smile", "happy"),
        "😍" to listOf("love", "heart", "eyes", "smile"),
        "🤩" to listOf("star", "struck", "wow"),
        "😘" to listOf("kiss", "love", "smile"),
        "😗" to listOf("kiss", "whistle"),
        "☺️" to listOf("smile", "relaxed", "happy"),
        "😚" to listOf("kiss", "closed", "eyes"),
        "😙" to listOf("kiss", "smile"),
        "🥲" to listOf("tear", "smile", "bittersweet"),
        "😋" to listOf("yum", "tongue", "tasty"),
        "😛" to listOf("tongue", "playful"),
        "😜" to listOf("wink", "tongue", "playful"),
        "🤪" to listOf("zany", "crazy", "wild"),
        "😝" to listOf("tongue", "closed", "eyes"),
        "🤑" to listOf("money", "rich", "cash"),
        "🤗" to listOf("hug", "smile"),
        "🤭" to listOf("oops", "giggle", "shy"),
        "🤫" to listOf("shush", "quiet", "secret"),
        "🤔" to listOf("think", "hmm", "wonder"),
        "🤐" to listOf("zip", "mouth", "silent"),
        "🤨" to listOf("eyebrow", "skeptical", "suspicious"),
        "😐" to listOf("neutral", "meh"),
        "😑" to listOf("expressionless", "blank"),
        "😶" to listOf("speechless", "blank", "no", "mouth"),
        "😏" to listOf("smirk", "smug"),
        "😒" to listOf("unamused", "meh", "annoyed"),
        "🙄" to listOf("roll", "eyes", "annoyed"),
        "😬" to listOf("grimace", "awkward"),
        "🤥" to listOf("lying", "pinocchio", "liar"),
        "😌" to listOf("relieved"),
        "😔" to listOf("pensive", "sad"),
        "😪" to listOf("sleepy", "tired"),
        "🤤" to listOf("drool", "yummy"),
        "😴" to listOf("sleep", "tired", "sleeping", "zzz"),
        "😷" to listOf("mask", "sick"),
        "🤒" to listOf("sick", "ill", "thermometer"),
        "🤕" to listOf("hurt", "bandage", "injured"),
        "🤢" to listOf("sick", "nausea", "gross"),
        "🤮" to listOf("vomit", "sick", "gross"),
        "🤧" to listOf("sneeze", "sick", "cold"),
        "🥵" to listOf("hot", "sweat", "heat"),
        "🥶" to listOf("cold", "freezing"),
        "😵" to listOf("dizzy", "knocked"),
        "🤯" to listOf("mind", "blown", "exploding", "head"),
        "🤠" to listOf("cowboy", "hat"),
        "🥳" to listOf("party", "celebrate", "birthday"),
        "😎" to listOf("cool", "sunglasses"),
        "🤓" to listOf("nerd", "geek", "glasses"),
        "🧐" to listOf("monocle", "fancy"),
        "😕" to listOf("confused"),
        "😟" to listOf("worried", "sad"),
        "🙁" to listOf("frown", "slight", "sad"),
        "😮" to listOf("open", "mouth", "surprised"),
        "😯" to listOf("hushed", "surprised"),
        "😲" to listOf("astonished", "shock"),
        "😳" to listOf("flushed", "blush", "embarrass"),
        "🥺" to listOf("pleading", "puppy", "cute"),
        "😦" to listOf("frowning", "open", "mouth"),
        "😧" to listOf("anguished"),
        "😨" to listOf("fearful", "scared"),
        "😰" to listOf("anxious", "sweat"),
        "😥" to listOf("sad", "relieved"),
        "😢" to listOf("cry", "sad", "tear"),
        "😭" to listOf("sob", "cry", "sad"),
        "😱" to listOf("scream", "fear", "shocked"),
        "😖" to listOf("confounded", "frustrated"),
        "😣" to listOf("persevere", "struggle"),
        "😞" to listOf("disappointed", "sad"),
        "😓" to listOf("downcast", "sweat", "sad"),
        "😩" to listOf("weary", "tired"),
        "😫" to listOf("tired", "weary"),
        "🥱" to listOf("yawn", "tired", "bored"),
        "😤" to listOf("triumph", "huff", "annoyed"),
        "😡" to listOf("angry", "mad", "rage"),
        "😠" to listOf("angry", "mad"),
        "🤬" to listOf("swear", "curse", "angry"),
        "😈" to listOf("devil", "imp", "evil"),
        "👿" to listOf("imp", "angry", "devil"),
        "💀" to listOf("skull", "death", "danger"),
        "☠️" to listOf("skull", "crossbones", "danger", "death"),
        "💩" to listOf("poo", "poop", "shit"),
        "🤡" to listOf("clown"),
        "👹" to listOf("ogre", "monster"),
        "👺" to listOf("goblin", "monster"),
        "👻" to listOf("ghost", "boo", "spooky"),
        "👽" to listOf("alien", "ufo", "space"),
        "👾" to listOf("alien", "space", "monster"),
        "🤖" to listOf("robot", "android"),

        // ---------------- Hands & body ----------------
        "👍" to listOf("thumbs", "up", "like", "ok", "yes"),
        "👎" to listOf("thumbs", "down", "dislike", "no"),
        "👌" to listOf("ok", "perfect"),
        "✌️" to listOf("peace", "victory"),
        "🤞" to listOf("crossed", "fingers", "luck", "hope"),
        "🤟" to listOf("love", "you", "rock"),
        "🤘" to listOf("rock", "horns"),
        "🤙" to listOf("call", "me", "shaka"),
        "👈" to listOf("point", "left"),
        "👉" to listOf("point", "right"),
        "👆" to listOf("point", "up"),
        "🖕" to listOf("middle", "finger", "rude"),
        "👇" to listOf("point", "down"),
        "👋" to listOf("wave", "hi", "hello", "bye"),
        "🤚" to listOf("raised", "back", "hand", "stop"),
        "🖐" to listOf("raised", "hand", "fingers", "splayed"),
        "✋" to listOf("raised", "hand", "stop", "high", "five"),
        "🖖" to listOf("vulcan", "spock", "salute"),
        "🙏" to listOf("pray", "thanks", "please"),
        "🙌" to listOf("raised", "hands", "praise"),
        "👏" to listOf("clap", "applause", "bravo"),
        "💪" to listOf("muscle", "strong", "flex"),
        "🤝" to listOf("handshake", "deal", "agree"),
        "🦾" to listOf("mechanical", "arm", "prosthetic"),
        "🦿" to listOf("mechanical", "leg", "prosthetic"),
        "🦵" to listOf("leg"),
        "🦶" to listOf("foot"),
        "👂" to listOf("ear"),
        "🦻" to listOf("ear", "hearing", "aid"),
        "👃" to listOf("nose"),
        "🧠" to listOf("brain", "mind"),
        "🫀" to listOf("anatomical", "heart"),
        "🫁" to listOf("lungs"),
        "🦷" to listOf("tooth"),
        "🦴" to listOf("bone"),
        "👀" to listOf("eyes", "look", "see"),
        "👁" to listOf("eye"),
        "👅" to listOf("tongue"),
        "👄" to listOf("mouth", "lips"),
        "💋" to listOf("kiss", "mark", "lips"),
        "🩸" to listOf("blood", "drop"),

        // ---------------- People & professions ----------------
        "👶" to listOf("baby"),
        "🧒" to listOf("child"),
        "👦" to listOf("boy"),
        "👧" to listOf("girl"),
        "🧑" to listOf("person", "adult"),
        "👨" to listOf("man"),
        "👩" to listOf("woman"),
        "🧓" to listOf("older", "person"),
        "👴" to listOf("old", "man", "grandpa"),
        "👵" to listOf("old", "woman", "grandma"),
        "👮" to listOf("police", "officer", "cop"),
        "🕵" to listOf("detective", "spy"),
        "💂" to listOf("guard", "soldier"),
        "👷" to listOf("construction", "worker"),
        "🤴" to listOf("prince"),
        "👸" to listOf("princess"),
        "🧙" to listOf("mage", "wizard"),
        "🧚" to listOf("fairy"),
        "🧛" to listOf("vampire"),
        "🧜" to listOf("merperson", "mermaid"),
        "🧝" to listOf("elf"),
        "🧞" to listOf("genie"),
        "🧟" to listOf("zombie"),
        "👼" to listOf("baby", "angel"),
        "🤰" to listOf("pregnant", "woman"),
        "🤱" to listOf("breast", "feeding"),
        "👰" to listOf("bride", "wedding"),
        "🤵" to listOf("groom", "tuxedo"),
        "💃" to listOf("dancer", "woman"),
        "🕺" to listOf("dancer", "man"),
        "👯" to listOf("dancers", "bunny", "ears"),

        // ---------------- Hearts & symbols of love ----------------
        "❤️" to listOf("heart", "love", "red"),
        "🧡" to listOf("heart", "orange"),
        "💛" to listOf("heart", "yellow"),
        "💚" to listOf("heart", "green"),
        "💙" to listOf("heart", "blue"),
        "💜" to listOf("heart", "purple"),
        "🖤" to listOf("heart", "black"),
        "🤍" to listOf("heart", "white"),
        "🤎" to listOf("heart", "brown"),
        "💔" to listOf("broken", "heart", "sad"),
        "❣️" to listOf("heart", "exclamation"),
        "💕" to listOf("hearts", "love"),
        "💞" to listOf("revolving", "hearts"),
        "💓" to listOf("beating", "heart"),
        "💗" to listOf("growing", "heart"),
        "💖" to listOf("sparkling", "heart", "love"),
        "💘" to listOf("heart", "arrow", "cupid"),
        "💝" to listOf("heart", "ribbon", "gift"),
        "💟" to listOf("heart", "decoration"),

        // ---------------- Emotion symbols ----------------
        "💯" to listOf("100", "hundred", "perfect", "score"),
        "💢" to listOf("anger"),
        "💥" to listOf("boom", "explosion", "collision"),
        "💫" to listOf("dizzy", "stars"),
        "💦" to listOf("sweat", "drops", "water"),
        "💨" to listOf("dash", "wind", "fast"),
        "💤" to listOf("zzz", "sleep"),

        // ---------------- Animals ----------------
        "🐶" to listOf("dog", "puppy"),
        "🐱" to listOf("cat", "kitten"),
        "🐭" to listOf("mouse"),
        "🐹" to listOf("hamster"),
        "🐰" to listOf("rabbit", "bunny"),
        "🦊" to listOf("fox"),
        "🐻" to listOf("bear"),
        "🐼" to listOf("panda"),
        "🐨" to listOf("koala"),
        "🐯" to listOf("tiger"),
        "🦁" to listOf("lion"),
        "🐮" to listOf("cow"),
        "🐷" to listOf("pig"),
        "🐽" to listOf("pig", "nose"),
        "🐸" to listOf("frog"),
        "🐵" to listOf("monkey"),
        "🙈" to listOf("monkey", "see", "no", "evil"),
        "🙉" to listOf("monkey", "hear", "no", "evil"),
        "🙊" to listOf("monkey", "speak", "no", "evil"),
        "🐒" to listOf("monkey", "tail"),
        "🐔" to listOf("chicken"),
        "🐧" to listOf("penguin"),
        "🐦" to listOf("bird"),
        "🐤" to listOf("chick", "baby", "bird"),
        "🐣" to listOf("hatching", "chick"),
        "🐥" to listOf("front", "chick"),
        "🦆" to listOf("duck"),
        "🦅" to listOf("eagle"),
        "🦉" to listOf("owl"),
        "🦇" to listOf("bat"),
        "🐺" to listOf("wolf"),
        "🐗" to listOf("boar", "pig"),
        "🐴" to listOf("horse", "face"),
        "🦄" to listOf("unicorn"),
        "🐝" to listOf("bee"),
        "🐛" to listOf("bug", "caterpillar"),
        "🦋" to listOf("butterfly"),
        "🐌" to listOf("snail"),
        "🐞" to listOf("ladybug", "beetle"),
        "🐜" to listOf("ant"),
        "🪰" to listOf("fly", "bug"),
        "🪱" to listOf("worm"),
        "🦗" to listOf("cricket"),
        "🕷" to listOf("spider"),
        "🦂" to listOf("scorpion"),
        "🐢" to listOf("turtle"),
        "🐍" to listOf("snake"),
        "🦎" to listOf("lizard", "gecko"),
        "🦖" to listOf("t-rex", "dinosaur"),
        "🦕" to listOf("sauropod", "dinosaur"),
        "🐙" to listOf("octopus"),
        "🦑" to listOf("squid"),
        "🦐" to listOf("shrimp"),
        "🦞" to listOf("lobster"),
        "🦀" to listOf("crab"),
        "🐡" to listOf("blowfish", "fish"),
        "🐠" to listOf("tropical", "fish"),
        "🐟" to listOf("fish"),
        "🐬" to listOf("dolphin"),
        "🐳" to listOf("whale", "spouting"),
        "🐋" to listOf("whale"),
        "🦈" to listOf("shark"),
        "🐊" to listOf("crocodile"),
        "🐅" to listOf("tiger"),
        "🐆" to listOf("leopard"),
        "🦓" to listOf("zebra"),
        "🦍" to listOf("gorilla"),
        "🦧" to listOf("orangutan"),
        "🦣" to listOf("mammoth"),
        "🐘" to listOf("elephant"),
        "🦛" to listOf("hippopotamus", "hippo"),
        "🦏" to listOf("rhinoceros", "rhino"),
        "🐪" to listOf("camel", "dromedary"),
        "🐫" to listOf("camel", "two", "hump"),
        "🦒" to listOf("giraffe"),
        "🦘" to listOf("kangaroo"),
        "🦬" to listOf("bison", "buffalo"),
        "🐃" to listOf("water", "buffalo"),
        "🐂" to listOf("ox", "bull"),
        "🐄" to listOf("cow"),
        "🐎" to listOf("horse"),
        "🐖" to listOf("pig"),
        "🐏" to listOf("ram", "sheep"),
        "🐑" to listOf("ewe", "sheep"),
        "🦙" to listOf("llama", "alpaca"),
        "🐐" to listOf("goat"),
        "🦌" to listOf("deer"),
        "🐕" to listOf("dog"),
        "🐩" to listOf("poodle"),
        "🦮" to listOf("guide", "dog"),
        "🐈" to listOf("cat"),
        "🐈‍⬛" to listOf("black", "cat"),
        "🐓" to listOf("rooster"),
        "🦃" to listOf("turkey"),
        "🦤" to listOf("dodo"),
        "🦚" to listOf("peacock"),
        "🦜" to listOf("parrot"),
        "🦢" to listOf("swan"),
        "🦩" to listOf("flamingo"),
        "🦝" to listOf("raccoon"),
        "🦨" to listOf("skunk"),
        "🦡" to listOf("badger"),
        "🦫" to listOf("beaver"),
        "🦦" to listOf("otter"),
        "🐇" to listOf("rabbit"),
        "🐁" to listOf("mouse"),
        "🐀" to listOf("rat"),
        "🐿" to listOf("chipmunk", "squirrel"),

        // ---------------- Plants ----------------
        "🌱" to listOf("seedling", "plant"),
        "🌲" to listOf("evergreen", "tree", "pine"),
        "🌳" to listOf("tree", "deciduous"),
        "🌴" to listOf("palm", "tree"),
        "🌵" to listOf("cactus"),
        "🌾" to listOf("rice", "ear", "grain"),
        "🌿" to listOf("herb", "leaves"),
        "☘️" to listOf("shamrock"),
        "🍀" to listOf("four", "leaf", "clover", "luck"),
        "🍁" to listOf("maple", "leaf"),
        "🍂" to listOf("fallen", "leaves", "autumn"),
        "🍃" to listOf("leaf", "wind"),
        "🪴" to listOf("potted", "plant"),
        "🌷" to listOf("tulip", "flower"),
        "🌹" to listOf("rose", "flower"),
        "🥀" to listOf("wilted", "flower"),
        "🌺" to listOf("hibiscus"),
        "🌸" to listOf("cherry", "blossom", "sakura"),
        "🌼" to listOf("blossom", "flower"),
        "🌻" to listOf("sunflower"),
        "💐" to listOf("bouquet", "flowers"),

        // ---------------- Food & drink ----------------
        "🍎" to listOf("apple", "fruit"),
        "🍐" to listOf("pear", "fruit"),
        "🍊" to listOf("tangerine", "orange", "fruit"),
        "🍋" to listOf("lemon", "fruit"),
        "🍌" to listOf("banana", "fruit"),
        "🍉" to listOf("watermelon", "fruit"),
        "🍇" to listOf("grapes", "fruit"),
        "🍓" to listOf("strawberry", "fruit"),
        "🫐" to listOf("blueberries", "fruit"),
        "🍈" to listOf("melon", "fruit"),
        "🍒" to listOf("cherries", "fruit"),
        "🍑" to listOf("peach", "fruit"),
        "🥭" to listOf("mango", "fruit"),
        "🍍" to listOf("pineapple", "fruit"),
        "🥥" to listOf("coconut", "fruit"),
        "🥝" to listOf("kiwi", "fruit"),
        "🍅" to listOf("tomato", "fruit"),
        "🍆" to listOf("eggplant", "aubergine"),
        "🥑" to listOf("avocado", "fruit"),
        "🥦" to listOf("broccoli", "vegetable"),
        "🥬" to listOf("leafy", "green", "vegetable"),
        "🥒" to listOf("cucumber", "vegetable"),
        "🌶" to listOf("chili", "pepper", "spicy"),
        "🫑" to listOf("bell", "pepper", "vegetable"),
        "🌽" to listOf("corn", "vegetable"),
        "🥕" to listOf("carrot", "vegetable"),
        "🫒" to listOf("olive"),
        "🧄" to listOf("garlic"),
        "🧅" to listOf("onion"),
        "🥔" to listOf("potato"),
        "🍠" to listOf("sweet", "potato"),
        "🥐" to listOf("croissant"),
        "🥯" to listOf("bagel"),
        "🍞" to listOf("bread", "loaf"),
        "🥖" to listOf("baguette"),
        "🥨" to listOf("pretzel"),
        "🧀" to listOf("cheese"),
        "🥚" to listOf("egg"),
        "🍳" to listOf("cooking", "egg", "fry"),
        "🧈" to listOf("butter"),
        "🥞" to listOf("pancakes"),
        "🧇" to listOf("waffle"),
        "🥓" to listOf("bacon"),
        "🥩" to listOf("steak", "meat"),
        "🍗" to listOf("poultry", "leg", "chicken"),
        "🍖" to listOf("meat", "bone"),
        "🦴" to listOf("bone"),
        "🌭" to listOf("hot", "dog"),
        "🍔" to listOf("burger", "food"),
        "🍟" to listOf("fries", "chips", "food"),
        "🍕" to listOf("pizza", "food"),
        "🥪" to listOf("sandwich"),
        "🥙" to listOf("stuffed", "flatbread", "kebab"),
        "🧆" to listOf("falafel"),
        "🌮" to listOf("taco", "food"),
        "🌯" to listOf("burrito"),
        "🫔" to listOf("tamale"),
        "🥗" to listOf("salad", "green"),
        "🥘" to listOf("paella", "pan", "food"),
        "🫕" to listOf("fondue", "pot"),
        "🥫" to listOf("canned", "food"),
        "🍝" to listOf("spaghetti", "pasta"),
        "🍜" to listOf("ramen", "noodle"),
        "🍲" to listOf("stew", "pot"),
        "🍛" to listOf("curry", "rice"),
        "🍣" to listOf("sushi", "food"),
        "🍱" to listOf("bento", "box"),
        "🥟" to listOf("dumpling"),
        "🦪" to listOf("oyster"),
        "🍤" to listOf("fried", "shrimp", "tempura"),
        "🍙" to listOf("rice", "ball"),
        "🍚" to listOf("cooked", "rice"),
        "🍘" to listOf("rice", "cracker"),
        "🍥" to listOf("fish", "cake"),
        "🥠" to listOf("fortune", "cookie"),
        "🥮" to listOf("moon", "cake"),
        "🍢" to listOf("oden"),
        "🍡" to listOf("dango"),
        "🍧" to listOf("shaved", "ice"),
        "🍨" to listOf("ice", "cream"),
        "🍦" to listOf("soft", "ice", "cream"),
        "🥧" to listOf("pie"),
        "🧁" to listOf("cupcake"),
        "🍰" to listOf("cake", "slice", "dessert"),
        "🎂" to listOf("cake", "birthday"),
        "🍮" to listOf("custard", "pudding"),
        "🍭" to listOf("lollipop"),
        "🍬" to listOf("candy", "sweet"),
        "🍫" to listOf("chocolate", "bar"),
        "🍿" to listOf("popcorn"),
        "🍩" to listOf("doughnut", "donut"),
        "🍪" to listOf("cookie", "biscuit"),
        "🌰" to listOf("chestnut"),
        "🥜" to listOf("peanuts"),
        "🍯" to listOf("honey", "pot"),
        "🥛" to listOf("milk", "drink"),
        "🍼" to listOf("baby", "bottle"),
        "☕" to listOf("coffee", "drink", "hot"),
        "🍵" to listOf("tea", "drink"),
        "🧃" to listOf("juice", "box"),
        "🥤" to listOf("cup", "straw", "soda"),
        "🧋" to listOf("bubble", "tea"),
        "🍶" to listOf("sake"),
        "🍺" to listOf("beer", "drink"),
        "🍻" to listOf("beers", "cheers"),
        "🥂" to listOf("clink", "glasses", "champagne"),
        "🍷" to listOf("wine", "drink"),
        "🥃" to listOf("tumbler", "whiskey"),
        "🍸" to listOf("cocktail", "martini"),
        "🍹" to listOf("tropical", "drink"),

        // ---------------- Activities & sports ----------------
        "⚽" to listOf("soccer", "football", "ball"),
        "🏀" to listOf("basketball", "ball"),
        "🏈" to listOf("football", "ball"),
        "⚾" to listOf("baseball", "ball"),
        "🥎" to listOf("softball"),
        "🎾" to listOf("tennis", "ball"),
        "🏐" to listOf("volleyball", "ball"),
        "🏉" to listOf("rugby"),
        "🥏" to listOf("frisbee", "flying", "disc"),
        "🎱" to listOf("pool", "billiards", "8", "ball"),
        "🪀" to listOf("yo-yo"),
        "🏓" to listOf("ping", "pong", "table", "tennis"),
        "🏸" to listOf("badminton"),
        "🏒" to listOf("ice", "hockey"),
        "🏑" to listOf("field", "hockey"),
        "🥍" to listOf("lacrosse"),
        "🏏" to listOf("cricket"),
        "🪃" to listOf("boomerang"),
        "🥅" to listOf("goal", "net"),
        "⛳" to listOf("flag", "hole", "golf"),
        "🪁" to listOf("kite"),
        "🏹" to listOf("bow", "arrow", "archery"),
        "🎣" to listOf("fishing", "rod"),
        "🤿" to listOf("diving", "mask"),
        "🥊" to listOf("boxing", "glove"),
        "🥋" to listOf("martial", "arts", "karate"),
        "🎽" to listOf("running", "shirt"),
        "🛹" to listOf("skateboard"),
        "🛷" to listOf("sled"),
        "⛸" to listOf("ice", "skate"),
        "🥌" to listOf("curling", "stone"),
        "🎿" to listOf("ski", "skis"),
        "⛷" to listOf("skier"),
        "🏂" to listOf("snowboarder"),
        "🪂" to listOf("parachute"),
        "🏋" to listOf("weight", "lift"),
        "🤼" to listOf("wrestling"),
        "🤸" to listOf("cartwheel"),
        "⛹" to listOf("bounce", "ball"),
        "🤺" to listOf("fencing"),
        "🤾" to listOf("handball"),
        "🏌" to listOf("golf"),
        "🏇" to listOf("horse", "racing"),
        "🧘" to listOf("yoga", "lotus"),
        "🏄" to listOf("surf", "surfing"),
        "🏊" to listOf("swim", "swimming"),
        "🤽" to listOf("water", "polo"),
        "🚣" to listOf("row", "boat"),
        "🧗" to listOf("climb", "climbing"),
        "🚵" to listOf("mountain", "bike"),
        "🚴" to listOf("bike", "cycling"),
        "🏆" to listOf("trophy", "win", "prize"),
        "🥇" to listOf("gold", "medal", "first"),
        "🥈" to listOf("silver", "medal", "second"),
        "🥉" to listOf("bronze", "medal", "third"),
        "🏅" to listOf("sports", "medal"),
        "🎖" to listOf("military", "medal"),
        "🏵" to listOf("rosette"),
        "🎗" to listOf("reminder", "ribbon"),
        "🎫" to listOf("ticket"),
        "🎟" to listOf("admission", "ticket"),
        "🎪" to listOf("circus", "tent"),
        "🤹" to listOf("juggle", "juggling"),
        "🎭" to listOf("performing", "arts", "masks"),
        "🩰" to listOf("ballet", "shoes"),
        "🎨" to listOf("art", "palette", "paint"),
        "🎬" to listOf("clapper", "board", "movie"),
        "🎤" to listOf("microphone", "mic", "sing"),
        "🎧" to listOf("headphones", "music"),
        "🎼" to listOf("musical", "score"),
        "🎹" to listOf("piano", "keyboard"),
        "🥁" to listOf("drum"),
        "🪘" to listOf("long", "drum"),
        "🎷" to listOf("saxophone"),
        "🎺" to listOf("trumpet"),
        "🪗" to listOf("accordion"),
        "🎸" to listOf("guitar"),
        "🪕" to listOf("banjo"),
        "🎻" to listOf("violin"),
        "🎲" to listOf("dice", "game"),
        "♟" to listOf("chess", "pawn"),
        "🎯" to listOf("dart", "bullseye", "target"),
        "🎳" to listOf("bowling"),
        "🎮" to listOf("game", "controller", "video"),
        "🕹" to listOf("joystick"),
        "🧩" to listOf("puzzle", "piece"),
        "🧸" to listOf("teddy", "bear", "toy"),
        "🪅" to listOf("piñata"),
        "🪆" to listOf("nesting", "dolls"),
        "🎵" to listOf("music", "note"),
        "🎶" to listOf("music", "notes"),

        // ---------------- Travel, transport & places ----------------
        "🚗" to listOf("car"),
        "🚕" to listOf("taxi"),
        "🚙" to listOf("suv"),
        "🚌" to listOf("bus"),
        "🚎" to listOf("trolleybus"),
        "🏎" to listOf("racing", "car"),
        "🚓" to listOf("police", "car"),
        "🚑" to listOf("ambulance"),
        "🚒" to listOf("fire", "engine", "truck"),
        "🚐" to listOf("minibus"),
        "🛻" to listOf("pickup", "truck"),
        "🚚" to listOf("delivery", "truck"),
        "🚛" to listOf("articulated", "lorry"),
        "🚜" to listOf("tractor"),
        "🛴" to listOf("scooter", "kick"),
        "🚲" to listOf("bicycle", "bike"),
        "🛵" to listOf("motor", "scooter"),
        "🏍" to listOf("motorcycle"),
        "🛺" to listOf("auto", "rickshaw"),
        "🚨" to listOf("police", "light", "siren"),
        "🚔" to listOf("oncoming", "police", "car"),
        "🚍" to listOf("oncoming", "bus"),
        "🚘" to listOf("oncoming", "car"),
        "🚖" to listOf("oncoming", "taxi"),
        "🚡" to listOf("aerial", "tramway"),
        "🚠" to listOf("mountain", "cableway"),
        "🚟" to listOf("suspension", "railway"),
        "🚃" to listOf("railway", "car"),
        "🚋" to listOf("tram", "car"),
        "🚞" to listOf("mountain", "railway"),
        "🚝" to listOf("monorail"),
        "🚄" to listOf("high-speed", "train"),
        "🚅" to listOf("bullet", "train"),
        "🚈" to listOf("light", "rail"),
        "🚂" to listOf("locomotive", "steam"),
        "🚆" to listOf("train"),
        "🚇" to listOf("metro", "subway"),
        "🚊" to listOf("tram"),
        "🚉" to listOf("station"),
        "✈" to listOf("plane", "airplane"),
        "✈️" to listOf("plane", "airplane"),
        "🛫" to listOf("takeoff", "departure"),
        "🛬" to listOf("landing", "arrival"),
        "🛩" to listOf("small", "airplane"),
        "🛰" to listOf("satellite"),
        "🚀" to listOf("rocket", "space"),
        "🛸" to listOf("ufo", "saucer"),
        "🚁" to listOf("helicopter"),
        "🛶" to listOf("canoe"),
        "⛵" to listOf("sailboat"),
        "🚤" to listOf("speedboat"),
        "🛥" to listOf("motor", "boat"),
        "🛳" to listOf("passenger", "ship"),
        "⛴" to listOf("ferry"),
        "🚢" to listOf("ship", "boat"),
        "⚓" to listOf("anchor"),
        "⛽" to listOf("fuel", "pump"),
        "🚧" to listOf("construction", "barrier"),
        "🚦" to listOf("vertical", "traffic", "light"),
        "🚥" to listOf("horizontal", "traffic", "light"),
        "🚏" to listOf("bus", "stop"),
        "🗺" to listOf("map", "world"),
        "🗿" to listOf("moai", "statue"),
        "🗽" to listOf("statue", "liberty"),
        "🗼" to listOf("tokyo", "tower"),
        "🏰" to listOf("castle"),
        "🏯" to listOf("japanese", "castle"),
        "🏟" to listOf("stadium"),
        "🎡" to listOf("ferris", "wheel"),
        "🎢" to listOf("roller", "coaster"),
        "🎠" to listOf("carousel", "horse"),
        "⛲" to listOf("fountain"),
        "⛱" to listOf("beach", "umbrella"),
        "🏖" to listOf("beach", "umbrella"),
        "🏝" to listOf("desert", "island"),
        "🏜" to listOf("desert"),
        "🌋" to listOf("volcano"),
        "⛰" to listOf("mountain"),
        "🏔" to listOf("snow", "capped", "mountain"),
        "🗻" to listOf("mount", "fuji"),
        "🏕" to listOf("camping"),
        "⛺" to listOf("tent"),
        "🏠" to listOf("house", "home"),
        "🏡" to listOf("house", "garden"),
        "🏘" to listOf("houses"),
        "🏚" to listOf("derelict", "house"),
        "🏗" to listOf("construction"),
        "🏭" to listOf("factory"),
        "🏢" to listOf("office", "building"),
        "🏬" to listOf("department", "store"),
        "🏣" to listOf("japanese", "post", "office"),
        "🏤" to listOf("post", "office"),
        "🏥" to listOf("hospital"),
        "🏦" to listOf("bank"),
        "🏨" to listOf("hotel"),
        "🏪" to listOf("convenience", "store"),
        "🏫" to listOf("school"),
        "🏩" to listOf("love", "hotel"),
        "💒" to listOf("wedding", "chapel"),
        "🏛" to listOf("classical", "building"),
        "⛪" to listOf("church"),
        "🕌" to listOf("mosque"),
        "🕍" to listOf("synagogue"),
        "🛕" to listOf("hindu", "temple"),
        "🕋" to listOf("kaaba"),
        "⛩" to listOf("shinto", "shrine"),
        "🌁" to listOf("foggy"),
        "🌃" to listOf("night", "stars"),
        "🏙" to listOf("cityscape"),
        "🌄" to listOf("sunrise", "mountain"),
        "🌅" to listOf("sunrise"),

        // ---------------- Sky & weather ----------------
        "🌑" to listOf("new", "moon"),
        "🌒" to listOf("waxing", "crescent", "moon"),
        "🌓" to listOf("first", "quarter", "moon"),
        "🌔" to listOf("waxing", "gibbous", "moon"),
        "🌕" to listOf("full", "moon"),
        "🌖" to listOf("waning", "gibbous", "moon"),
        "🌗" to listOf("last", "quarter", "moon"),
        "🌘" to listOf("waning", "crescent", "moon"),
        "🌙" to listOf("moon", "night"),
        "🌚" to listOf("new", "moon", "face"),
        "🌛" to listOf("first", "quarter", "face"),
        "🌜" to listOf("last", "quarter", "face"),
        "🌝" to listOf("full", "moon", "face"),
        "🌞" to listOf("sun", "face"),
        "🌟" to listOf("star", "glow", "sparkle"),
        "⭐" to listOf("star"),
        "✨" to listOf("sparkles", "shine"),
        "☀️" to listOf("sun", "sunny", "weather"),
        "🌤" to listOf("sun", "small", "cloud"),
        "⛅" to listOf("sun", "behind", "cloud"),
        "🌥" to listOf("sun", "behind", "large", "cloud"),
        "☁️" to listOf("cloud", "weather"),
        "🌦" to listOf("sun", "rain"),
        "🌧" to listOf("cloud", "rain"),
        "⛈" to listOf("cloud", "lightning", "rain"),
        "🌩" to listOf("cloud", "lightning"),
        "🌨" to listOf("cloud", "snow"),
        "❄️" to listOf("snow", "cold", "snowflake"),
        "☃️" to listOf("snowman"),
        "⛄" to listOf("snowman", "no", "snow"),
        "🌬" to listOf("wind", "blowing"),
        "💨" to listOf("dash", "wind", "fast"),
        "⚡" to listOf("lightning", "bolt", "fast", "zap"),
        "🔥" to listOf("fire", "hot", "lit", "flame"),
        "💧" to listOf("droplet"),
        "🌊" to listOf("wave", "ocean", "water"),
        "🌪" to listOf("tornado"),
        "🌫" to listOf("fog"),
        "🌈" to listOf("rainbow", "pride"),

        // ---------------- Objects ----------------
        "💡" to listOf("idea", "bulb", "light"),
        "🔦" to listOf("flashlight", "torch"),
        "🕯" to listOf("candle"),
        "🪔" to listOf("diya", "lamp"),
        "📱" to listOf("phone", "mobile", "smartphone"),
        "📲" to listOf("phone", "incoming", "call"),
        "💻" to listOf("laptop", "computer"),
        "⌨" to listOf("keyboard"),
        "🖥" to listOf("desktop", "computer"),
        "🖨" to listOf("printer"),
        "🖱" to listOf("computer", "mouse"),
        "🖲" to listOf("trackball"),
        "🗜" to listOf("clamp", "compression"),
        "💽" to listOf("minidisc"),
        "💾" to listOf("floppy", "disk", "save"),
        "💿" to listOf("cd"),
        "📀" to listOf("dvd"),
        "📼" to listOf("video", "cassette"),
        "📷" to listOf("camera", "photo"),
        "📸" to listOf("camera", "flash"),
        "📹" to listOf("video", "camera"),
        "🎥" to listOf("camera", "movie", "video"),
        "📽" to listOf("film", "projector"),
        "🎞" to listOf("film", "frames"),
        "📞" to listOf("telephone", "receiver"),
        "☎" to listOf("phone", "telephone"),
        "📟" to listOf("pager"),
        "📠" to listOf("fax"),
        "📺" to listOf("tv", "television"),
        "📻" to listOf("radio"),
        "🎙" to listOf("studio", "microphone"),
        "🎚" to listOf("level", "slider"),
        "🎛" to listOf("control", "knobs"),
        "🧭" to listOf("compass"),
        "⏱" to listOf("stopwatch"),
        "⏲" to listOf("timer"),
        "⏰" to listOf("clock", "alarm", "time"),
        "🕰" to listOf("mantelpiece", "clock"),
        "⌛" to listOf("hourglass", "done"),
        "⏳" to listOf("hourglass", "time", "waiting"),
        "📡" to listOf("satellite", "antenna"),
        "🔋" to listOf("battery"),
        "🪫" to listOf("low", "battery"),
        "🔌" to listOf("plug", "electric"),
        "💎" to listOf("gem", "diamond"),
        "⚖" to listOf("balance", "scale", "justice"),
        "🪜" to listOf("ladder"),
        "🧰" to listOf("toolbox"),
        "🔧" to listOf("wrench", "spanner"),
        "🪛" to listOf("screwdriver"),
        "🔨" to listOf("hammer"),
        "⚒" to listOf("hammer", "pick"),
        "🛠" to listOf("hammer", "wrench"),
        "⛏" to listOf("pick"),
        "🪚" to listOf("saw"),
        "🔩" to listOf("nut", "bolt"),
        "⚙" to listOf("gear", "settings"),
        "🪤" to listOf("mouse", "trap"),
        "🧱" to listOf("brick"),
        "⛓" to listOf("chains"),
        "🧲" to listOf("magnet"),
        "🔫" to listOf("water", "pistol"),
        "💣" to listOf("bomb"),
        "🧨" to listOf("firecracker"),
        "🪓" to listOf("axe"),
        "🔪" to listOf("kitchen", "knife"),
        "🗡" to listOf("dagger"),
        "⚔" to listOf("crossed", "swords"),
        "🛡" to listOf("shield"),
        "🚬" to listOf("cigarette"),
        "⚰" to listOf("coffin"),
        "🪦" to listOf("headstone"),
        "⚱" to listOf("urn"),
        "🏺" to listOf("amphora"),
        "🔮" to listOf("crystal", "ball"),
        "📿" to listOf("prayer", "beads"),
        "🧿" to listOf("nazar", "amulet"),
        "💈" to listOf("barber", "pole"),
        "⚗" to listOf("alchemy", "alembic"),
        "🔭" to listOf("telescope"),
        "🔬" to listOf("microscope"),
        "🕳" to listOf("hole"),
        "🩹" to listOf("bandage", "adhesive"),
        "🩺" to listOf("stethoscope"),
        "💊" to listOf("pill", "medicine"),
        "💉" to listOf("syringe", "vaccine"),
        "🧬" to listOf("dna"),
        "🦠" to listOf("microbe", "virus", "germ"),
        "🧫" to listOf("petri", "dish"),
        "🧪" to listOf("test", "tube"),
        "🌡" to listOf("thermometer"),
        "🧹" to listOf("broom"),
        "🧺" to listOf("basket"),
        "🧻" to listOf("toilet", "paper"),
        "🚽" to listOf("toilet"),
        "🚰" to listOf("potable", "water"),
        "🚿" to listOf("shower"),
        "🛁" to listOf("bathtub"),
        "🛀" to listOf("bath"),
        "🧼" to listOf("soap"),
        "🪥" to listOf("toothbrush"),
        "🪒" to listOf("razor"),
        "🧽" to listOf("sponge"),
        "🪣" to listOf("bucket"),
        "🧴" to listOf("lotion", "bottle"),
        "🛎" to listOf("bellhop", "bell"),
        "🔑" to listOf("key", "lock"),
        "🗝" to listOf("old", "key"),
        "🚪" to listOf("door"),
        "🪑" to listOf("chair"),
        "🛋" to listOf("couch", "lamp"),
        "🛏" to listOf("bed"),
        "🛌" to listOf("person", "sleeping"),
        "🪞" to listOf("mirror"),
        "🪟" to listOf("window"),
        "🛍" to listOf("shopping", "bags"),
        "🛒" to listOf("cart", "shopping"),
        "🎁" to listOf("gift", "present", "wrapped"),
        "🎈" to listOf("balloon"),
        "🎏" to listOf("carp", "streamer"),
        "🎀" to listOf("ribbon", "bow"),
        "🪄" to listOf("magic", "wand"),
        "🎊" to listOf("confetti", "party", "celebrate"),
        "🎉" to listOf("party", "tada", "celebrate"),
        "🎎" to listOf("japanese", "dolls"),
        "🏮" to listOf("red", "paper", "lantern"),

        // ---------------- Currency, money, books, writing ----------------
        "💰" to listOf("money", "bag", "cash"),
        "💳" to listOf("credit", "card"),
        "💵" to listOf("dollar", "banknote"),
        "💴" to listOf("yen", "banknote"),
        "💶" to listOf("euro", "banknote"),
        "💷" to listOf("pound", "banknote"),
        "💸" to listOf("money", "wings"),
        "💱" to listOf("currency", "exchange"),
        "💲" to listOf("dollar", "sign"),
        "📚" to listOf("books", "study"),
        "📖" to listOf("open", "book"),
        "📕" to listOf("closed", "book"),
        "📗" to listOf("green", "book"),
        "📘" to listOf("blue", "book"),
        "📙" to listOf("orange", "book"),
        "📓" to listOf("notebook"),
        "📒" to listOf("ledger"),
        "📔" to listOf("notebook", "decorative"),
        "📃" to listOf("page", "curl"),
        "📜" to listOf("scroll"),
        "📄" to listOf("page"),
        "📰" to listOf("newspaper"),
        "🗞" to listOf("rolled", "newspaper"),
        "📑" to listOf("bookmark", "tabs"),
        "🔖" to listOf("bookmark"),
        "🏷" to listOf("label", "tag"),
        "📦" to listOf("package", "box"),
        "📨" to listOf("incoming", "envelope"),
        "📧" to listOf("email", "mail"),
        "📩" to listOf("envelope", "arrow"),
        "📤" to listOf("outbox", "tray"),
        "📥" to listOf("inbox", "tray"),
        "📮" to listOf("postbox"),
        "🗳" to listOf("ballot", "box"),
        "✏️" to listOf("pencil", "write"),
        "✒️" to listOf("pen", "write"),
        "🖋" to listOf("fountain", "pen"),
        "🖊" to listOf("pen", "ballpoint"),
        "🖌" to listOf("paintbrush"),
        "🖍" to listOf("crayon"),
        "📝" to listOf("memo", "note", "write"),
        "💼" to listOf("briefcase", "work"),
        "📁" to listOf("file", "folder"),
        "📂" to listOf("open", "folder"),
        "🗂" to listOf("card", "index"),
        "📅" to listOf("calendar", "date"),
        "📆" to listOf("tear-off", "calendar"),
        "🗒" to listOf("spiral", "notepad"),
        "🗓" to listOf("spiral", "calendar"),
        "📇" to listOf("card", "index"),
        "📈" to listOf("chart", "increasing"),
        "📉" to listOf("chart", "decreasing"),
        "📊" to listOf("bar", "chart"),
        "📋" to listOf("clipboard"),
        "📌" to listOf("pushpin"),
        "📍" to listOf("round", "pushpin"),
        "📎" to listOf("paperclip"),
        "🖇" to listOf("linked", "paperclips"),
        "📏" to listOf("straight", "ruler"),
        "📐" to listOf("triangular", "ruler"),
        "✂️" to listOf("scissors", "cut"),

        // ---------------- Symbols ----------------
        "☮️" to listOf("peace", "symbol"),
        "✝️" to listOf("latin", "cross"),
        "☪️" to listOf("star", "crescent"),
        "🕉" to listOf("om"),
        "☸️" to listOf("wheel", "dharma"),
        "✡️" to listOf("star", "david"),
        "🔯" to listOf("six", "pointed", "star"),
        "🕎" to listOf("menorah"),
        "☯️" to listOf("yin", "yang"),
        "☦️" to listOf("orthodox", "cross"),
        "🛐" to listOf("place", "worship"),
        "⛎" to listOf("ophiuchus"),
        "♈" to listOf("aries"),
        "♉" to listOf("taurus"),
        "♊" to listOf("gemini"),
        "♋" to listOf("cancer"),
        "♌" to listOf("leo"),
        "♍" to listOf("virgo"),
        "♎" to listOf("libra"),
        "♏" to listOf("scorpio"),
        "♐" to listOf("sagittarius"),
        "♑" to listOf("capricorn"),
        "♒" to listOf("aquarius"),
        "♓" to listOf("pisces"),
        "🆔" to listOf("id", "button"),
        "⚛️" to listOf("atom", "symbol"),
        "☢️" to listOf("radioactive"),
        "☣️" to listOf("biohazard"),
        "📴" to listOf("mobile", "phone", "off"),
        "📳" to listOf("vibration", "mode"),
        "✴️" to listOf("eight", "pointed", "star"),
        "🆚" to listOf("vs", "button"),
        "💮" to listOf("white", "flower"),
        "🆑" to listOf("cl", "button"),
        "🆘" to listOf("sos", "help"),
        "❌" to listOf("x", "no", "wrong", "cross"),
        "⭕" to listOf("hollow", "red", "circle"),
        "🛑" to listOf("stop", "sign"),
        "⛔" to listOf("no", "entry"),
        "📛" to listOf("name", "badge"),
        "🚫" to listOf("no", "forbidden", "prohibited"),
        "♨️" to listOf("hot", "springs"),
        "🚷" to listOf("no", "pedestrians"),
        "🚯" to listOf("no", "littering"),
        "🚳" to listOf("no", "bicycles"),
        "🚱" to listOf("non-potable", "water"),
        "🔞" to listOf("no", "minors", "18"),
        "📵" to listOf("no", "mobile", "phones"),
        "🚭" to listOf("no", "smoking"),
        "❗" to listOf("exclamation", "mark"),
        "❕" to listOf("white", "exclamation"),
        "❓" to listOf("question", "mark"),
        "❔" to listOf("white", "question"),
        "‼️" to listOf("double", "exclamation"),
        "⁉️" to listOf("exclamation", "question"),
        "🔅" to listOf("dim", "button"),
        "🔆" to listOf("bright", "button"),
        "〽️" to listOf("part", "alternation", "mark"),
        "⚠️" to listOf("warning"),
        "🚸" to listOf("children", "crossing"),
        "🔱" to listOf("trident"),
        "⚜️" to listOf("fleur-de-lis"),
        "🔰" to listOf("japanese", "symbol"),
        "♻️" to listOf("recycle", "green"),
        "✅" to listOf("check", "ok", "yes", "tick"),
        "❇️" to listOf("sparkle"),
        "✳️" to listOf("eight-spoked", "asterisk"),
        "❎" to listOf("cross", "mark"),
        "🌐" to listOf("globe", "meridians"),
        "💠" to listOf("diamond", "dot"),
        "Ⓜ️" to listOf("circled", "m"),
        "🌀" to listOf("cyclone"),
        "🏧" to listOf("atm"),
        "🚾" to listOf("water", "closet", "wc"),
        "♿" to listOf("wheelchair", "accessible"),
        "🅿️" to listOf("p", "parking"),
        "🛗" to listOf("elevator"),
        "🛂" to listOf("passport", "control"),
        "🛃" to listOf("customs"),
        "🛄" to listOf("baggage", "claim"),
        "🛅" to listOf("left", "luggage"),
        "🚹" to listOf("men", "restroom"),
        "🚺" to listOf("women", "restroom"),
        "🚼" to listOf("baby", "symbol"),
        "⚧" to listOf("transgender"),
        "🚻" to listOf("restroom"),
        "🚮" to listOf("litter", "bin"),
        "🎦" to listOf("cinema"),
        "📶" to listOf("antenna", "bars"),
        "🔣" to listOf("input", "symbols"),
        "ℹ️" to listOf("info", "information"),
        "🔤" to listOf("input", "latin", "letters"),
        "🔡" to listOf("input", "lowercase"),
        "🔠" to listOf("input", "uppercase"),
        "🆖" to listOf("ng", "button"),
        "🆗" to listOf("ok", "button"),
        "🆙" to listOf("up", "button"),
        "🆒" to listOf("cool", "button"),
        "🆕" to listOf("new", "button"),
        "🆓" to listOf("free", "button"),
        "0️⃣" to listOf("0", "zero"),
        "1️⃣" to listOf("1", "one"),
        "2️⃣" to listOf("2", "two"),
        "3️⃣" to listOf("3", "three"),
        "4️⃣" to listOf("4", "four"),
        "5️⃣" to listOf("5", "five"),
        "6️⃣" to listOf("6", "six"),
        "7️⃣" to listOf("7", "seven"),
        "8️⃣" to listOf("8", "eight"),
        "9️⃣" to listOf("9", "nine"),
        "🔟" to listOf("10", "ten"),
        "🔔" to listOf("bell", "notification"),
        "🔕" to listOf("bell", "no", "slash"),
        "🔇" to listOf("mute", "silent", "no", "sound"),
        "🔈" to listOf("speaker", "low"),
        "🔉" to listOf("speaker", "medium"),
        "🔊" to listOf("speaker", "loud", "sound"),
        "⌚" to listOf("watch", "time"),
        "📿" to listOf("prayer", "beads"),

        // ---------------- People & body extras (gestures, professions) ----------------
        "🫶" to listOf("heart", "hands", "love"),
        "🤲" to listOf("palms", "up", "together"),
        "👐" to listOf("open", "hands"),
        "👊" to listOf("fist", "punch", "bump"),
        "✊" to listOf("raised", "fist", "power"),
        "🤛" to listOf("left", "fist", "bump"),
        "🤜" to listOf("right", "fist", "bump"),
        "🤌" to listOf("pinched", "fingers", "italy"),
        "🤏" to listOf("pinch"),
        "🫰" to listOf("fingers", "crossed", "snap", "money"),
        "☝️" to listOf("index", "point", "up"),
        "🫲" to listOf("leftwards", "hand"),
        "🫱" to listOf("rightwards", "hand"),
        "🫳" to listOf("palm", "down"),
        "🫴" to listOf("palm", "up"),
        "💅" to listOf("nail", "polish"),
        "🤳" to listOf("selfie"),
        "😺" to listOf("smiling", "cat"),
        "😸" to listOf("grinning", "cat"),
        "😹" to listOf("joy", "cat", "tears"),
        "😻" to listOf("heart", "eyes", "cat"),
        "😼" to listOf("wry", "cat", "smirk"),
        "😽" to listOf("kissing", "cat"),
        "🙀" to listOf("weary", "cat", "shocked"),
        "😿" to listOf("crying", "cat"),
        "😾" to listOf("pouting", "cat"),
        "👶" to listOf("baby"),
        "🧒" to listOf("child"),
        "👦" to listOf("boy"),
        "👧" to listOf("girl"),
        "🧑" to listOf("person", "adult"),
        "👱" to listOf("blond", "person"),
        "👨" to listOf("man"),
        "🧔" to listOf("beard", "person"),
        "👩" to listOf("woman"),
        "🧓" to listOf("older", "person"),
        "👴" to listOf("old", "man", "grandpa"),
        "👵" to listOf("old", "woman", "grandma"),
        "🙍" to listOf("frowning", "person"),
        "🙎" to listOf("pouting", "person"),
        "🙅" to listOf("no", "person", "gesture"),
        "🙆" to listOf("ok", "person", "gesture"),
        "💁" to listOf("tipping", "hand", "person"),
        "🙋" to listOf("raising", "hand", "person"),
        "🧏" to listOf("deaf", "person"),
        "🙇" to listOf("bowing", "person"),
        "🤦" to listOf("facepalm"),
        "🤷" to listOf("shrug"),
        "🧑‍⚕️" to listOf("health", "worker", "doctor", "nurse"),
        "👨‍⚕️" to listOf("doctor", "man"),
        "👩‍⚕️" to listOf("doctor", "woman", "nurse"),
        "🧑‍🎓" to listOf("student"),
        "👨‍🎓" to listOf("student", "man"),
        "👩‍🎓" to listOf("student", "woman"),
        "🧑‍🏫" to listOf("teacher"),
        "🧑‍⚖️" to listOf("judge"),
        "🧑‍🌾" to listOf("farmer"),
        "🧑‍🍳" to listOf("cook", "chef"),
        "🧑‍🔧" to listOf("mechanic"),
        "🧑‍🏭" to listOf("factory", "worker"),
        "🧑‍💼" to listOf("office", "worker"),
        "🧑‍🔬" to listOf("scientist"),
        "🧑‍💻" to listOf("technologist", "developer", "programmer"),
        "🧑‍🎤" to listOf("singer", "rockstar"),
        "🧑‍🎨" to listOf("artist", "painter"),
        "🧑‍✈️" to listOf("pilot"),
        "🧑‍🚀" to listOf("astronaut"),
        "🧑‍🚒" to listOf("firefighter"),
        "👮" to listOf("police", "officer", "cop"),
        "🕵️" to listOf("detective", "spy"),
        "💂" to listOf("guard", "soldier"),
        "🥷" to listOf("ninja"),
        "👷" to listOf("construction", "worker"),
        "🫅" to listOf("royal", "crown", "monarch"),
        "🤴" to listOf("prince"),
        "👸" to listOf("princess"),
        "👳" to listOf("turban", "person"),
        "👲" to listOf("skullcap", "person"),
        "🧕" to listOf("headscarf", "person"),
        "🤵" to listOf("tuxedo", "groom"),
        "👰" to listOf("bride", "veil", "wedding"),
        "🤰" to listOf("pregnant", "woman"),
        "🫃" to listOf("pregnant", "man"),
        "🫄" to listOf("pregnant", "person"),
        "🤱" to listOf("breast", "feeding"),
        "👼" to listOf("baby", "angel"),
        "🎅" to listOf("santa", "claus"),
        "🤶" to listOf("mrs", "claus"),
        "🧑‍🎄" to listOf("mx", "claus"),
        "🦸" to listOf("superhero"),
        "🦹" to listOf("supervillain"),
        "🧙" to listOf("mage", "wizard"),
        "🧚" to listOf("fairy"),
        "🧛" to listOf("vampire"),
        "🧜" to listOf("merperson", "mermaid"),
        "🧝" to listOf("elf"),
        "🧞" to listOf("genie"),
        "🧟" to listOf("zombie"),
        "🧌" to listOf("troll"),
        "💆" to listOf("massage", "face"),
        "💇" to listOf("haircut"),
        "🚶" to listOf("walking", "pedestrian"),
        "🧍" to listOf("standing", "person"),
        "🧎" to listOf("kneeling", "person"),
        "🏃" to listOf("running", "person"),
        "💃" to listOf("dancer", "woman"),
        "🕺" to listOf("dancer", "man"),
        "🕴️" to listOf("suspended", "businessman"),
        "👯" to listOf("dancers", "bunny", "ears"),
        "🧖" to listOf("sauna", "steam"),
        "👭" to listOf("women", "holding", "hands"),
        "👫" to listOf("woman", "man", "holding", "hands"),
        "👬" to listOf("men", "holding", "hands"),
        "💏" to listOf("kiss", "couple"),
        "💑" to listOf("couple", "heart"),
        "👪" to listOf("family"),
        "🗣️" to listOf("speaking", "head"),
        "👤" to listOf("silhouette", "bust"),
        "👥" to listOf("silhouettes", "busts"),
        "🫂" to listOf("hugging", "people"),
        "👣" to listOf("footprints"),

        // ---------------- Smileys / faces extras ----------------
        "🫠" to listOf("melting", "face"),
        "🫢" to listOf("open", "eyes", "hand", "over", "mouth"),
        "🫣" to listOf("peeking", "eye"),
        "🫡" to listOf("salute", "saluting"),
        "🫥" to listOf("dotted", "line", "face"),
        "😶‍🌫️" to listOf("face", "clouds"),
        "😮‍💨" to listOf("exhale", "exhaling", "face"),
        "🫨" to listOf("shaking", "face"),
        "🙂‍↔️" to listOf("shaking", "head", "no"),
        "🙂‍↕️" to listOf("nodding", "yes"),
        "🥴" to listOf("woozy", "face"),
        "😵‍💫" to listOf("knocked", "out", "spiral"),
        "🥸" to listOf("disguised", "face", "moustache"),
        "🫤" to listOf("diagonal", "mouth"),
        "🥹" to listOf("holding", "back", "tears"),
        "☹️" to listOf("frowning"),

        // ---------------- Animals / nature extras ----------------
        "🐻‍❄️" to listOf("polar", "bear"),
        "🪿" to listOf("goose"),
        "🐦‍⬛" to listOf("black", "bird"),
        "🪲" to listOf("beetle"),
        "🪳" to listOf("cockroach"),
        "🕸️" to listOf("spider", "web"),
        "🪼" to listOf("jellyfish"),
        "🐕‍🦺" to listOf("service", "dog"),
        "🪶" to listOf("feather"),
        "🕊️" to listOf("dove"),
        "🦝" to listOf("raccoon"),
        "🦨" to listOf("skunk"),
        "🦡" to listOf("badger"),
        "🦫" to listOf("beaver"),
        "🦦" to listOf("otter"),
        "🦥" to listOf("sloth"),
        "🐾" to listOf("paw", "prints"),
        "🐉" to listOf("dragon"),
        "🐲" to listOf("dragon", "face"),
        "🪵" to listOf("wood", "log"),
        "🎍" to listOf("pine", "decoration"),
        "🎋" to listOf("tanabata", "tree"),
        "🍄" to listOf("mushroom"),
        "🪸" to listOf("coral"),
        "🪨" to listOf("rock", "stone"),
        "🪻" to listOf("hyacinth"),
        "💫" to listOf("dizzy", "stars"),
        "🪐" to listOf("ringed", "planet", "saturn"),
        "☄️" to listOf("comet"),
        "🌎" to listOf("globe", "americas"),
        "🌍" to listOf("globe", "africa", "europe"),
        "🌏" to listOf("globe", "asia", "australia"),

        // ---------------- Food extras ----------------
        "🍏" to listOf("green", "apple"),
        "🫛" to listOf("pea", "pod"),
        "🫚" to listOf("ginger"),
        "🫙" to listOf("jar"),
        "🫗" to listOf("pouring", "liquid"),
        "🫘" to listOf("beans"),
        "🧉" to listOf("mate", "drink"),
        "🍾" to listOf("champagne", "bottle"),
        "🧊" to listOf("ice", "cube"),
        "🥄" to listOf("spoon"),
        "🍴" to listOf("fork", "knife"),
        "🍽️" to listOf("plate", "fork", "knife"),
        "🥢" to listOf("chopsticks"),
        "🧂" to listOf("salt"),

        // ---------------- Activity extras ----------------
        "🛼" to listOf("roller", "skate"),
        "🪈" to listOf("flute"),
        "🪩" to listOf("disco", "ball"),
        "🃏" to listOf("joker"),
        "🀄" to listOf("mahjong", "red", "dragon"),
        "🎴" to listOf("flower", "playing", "cards"),

        // ---------------- Travel extras ----------------
        "🦯" to listOf("white", "cane"),
        "🦽" to listOf("manual", "wheelchair"),
        "🦼" to listOf("motorized", "wheelchair"),
        "🛞" to listOf("wheel"),
        "💺" to listOf("seat"),
        "🛟" to listOf("ring", "buoy"),
        "🛖" to listOf("hut"),
        "🛤️" to listOf("railway", "track"),
        "🛣️" to listOf("motorway"),
        "🗾" to listOf("japan", "map"),
        "🎑" to listOf("moon", "ceremony"),
        "🏞️" to listOf("national", "park"),
        "🌠" to listOf("shooting", "star"),
        "🎇" to listOf("sparkler"),
        "🎆" to listOf("fireworks"),
        "🌌" to listOf("milky", "way", "galaxy"),
        "🌉" to listOf("bridge", "night"),

        // ---------------- Objects extras (clothing, stationery, technology) ----------------
        "🛜" to listOf("wireless"),
        "🪫" to listOf("low", "battery"),
        "🧯" to listOf("fire", "extinguisher"),
        "🛢️" to listOf("oil", "drum"),
        "🪙" to listOf("coin"),
        "🪜" to listOf("ladder"),
        "🪛" to listOf("screwdriver"),
        "🪤" to listOf("mouse", "trap"),
        "🪦" to listOf("headstone", "grave"),
        "🪬" to listOf("hamsa"),
        "🩻" to listOf("x-ray"),
        "🪠" to listOf("plunger"),
        "🪥" to listOf("toothbrush"),
        "🪒" to listOf("razor"),
        "🪣" to listOf("bucket"),
        "🛎️" to listOf("bellhop", "bell"),
        "🪧" to listOf("placard", "sign"),
        "🧷" to listOf("safety", "pin"),
        "🧮" to listOf("abacus"),
        "🪮" to listOf("pick", "comb"),
        "👜" to listOf("handbag"),
        "👛" to listOf("purse"),
        "👝" to listOf("clutch", "pouch"),
        "🎒" to listOf("backpack", "school", "bag"),
        "🧳" to listOf("luggage", "suitcase"),
        "👓" to listOf("glasses"),
        "🕶️" to listOf("sunglasses"),
        "🥽" to listOf("goggles"),
        "🦺" to listOf("safety", "vest"),
        "🥼" to listOf("lab", "coat"),
        "🥻" to listOf("sari"),
        "👔" to listOf("necktie", "shirt"),
        "👕" to listOf("t-shirt"),
        "👖" to listOf("jeans"),
        "🧣" to listOf("scarf"),
        "🧤" to listOf("gloves"),
        "🧥" to listOf("coat"),
        "🧦" to listOf("socks"),
        "👗" to listOf("dress"),
        "👘" to listOf("kimono"),
        "🥿" to listOf("flat", "shoe"),
        "👠" to listOf("heel", "shoe"),
        "👡" to listOf("sandal"),
        "👢" to listOf("boot"),
        "🥾" to listOf("hiking", "boot"),
        "👟" to listOf("running", "shoe", "sneaker"),
        "🩴" to listOf("flip", "flop", "thong"),
        "👞" to listOf("man", "shoe"),
        "👑" to listOf("crown"),
        "👒" to listOf("hat"),
        "🎩" to listOf("top", "hat"),
        "🎓" to listOf("graduation", "cap"),
        "🧢" to listOf("baseball", "cap"),
        "⛑️" to listOf("rescue", "helmet"),
        "🪖" to listOf("military", "helmet"),
        "💌" to listOf("love", "letter"),
        "🪪" to listOf("identification", "card"),
        "🪪" to listOf("id", "card"),

        // ---------------- Symbols extras (hearts, arrows, controls, shapes) ----------------
        "🩵" to listOf("light", "blue", "heart"),
        "🩶" to listOf("grey", "heart"),
        "🩷" to listOf("pink", "heart"),
        "🪯" to listOf("khanda"),
        "▶️" to listOf("play"),
        "⏸️" to listOf("pause"),
        "⏯️" to listOf("play", "pause"),
        "⏹️" to listOf("stop"),
        "⏺️" to listOf("record"),
        "⏭️" to listOf("next", "track"),
        "⏮️" to listOf("previous", "track"),
        "⏩" to listOf("fast", "forward"),
        "⏪" to listOf("fast", "reverse"),
        "⏫" to listOf("fast", "up"),
        "⏬" to listOf("fast", "down"),
        "◀️" to listOf("reverse", "left"),
        "🔼" to listOf("up", "button"),
        "🔽" to listOf("down", "button"),
        "➡️" to listOf("right", "arrow"),
        "⬅️" to listOf("left", "arrow"),
        "⬆️" to listOf("up", "arrow"),
        "⬇️" to listOf("down", "arrow"),
        "↗️" to listOf("up-right", "arrow"),
        "↘️" to listOf("down-right", "arrow"),
        "↙️" to listOf("down-left", "arrow"),
        "↖️" to listOf("up-left", "arrow"),
        "↕️" to listOf("up-down", "arrow"),
        "↔️" to listOf("left-right", "arrow"),
        "↪️" to listOf("right", "hook"),
        "↩️" to listOf("left", "hook"),
        "⤴️" to listOf("right", "arrow", "up"),
        "⤵️" to listOf("right", "arrow", "down"),
        "🔀" to listOf("shuffle"),
        "🔁" to listOf("repeat"),
        "🔂" to listOf("repeat", "single"),
        "🔄" to listOf("counterclockwise", "arrows"),
        "🔃" to listOf("clockwise", "arrows"),
        "➕" to listOf("plus"),
        "➖" to listOf("minus"),
        "➗" to listOf("divide"),
        "✖️" to listOf("multiply"),
        "🟰" to listOf("equals"),
        "♾️" to listOf("infinity"),
        "💱" to listOf("currency", "exchange"),
        "™️" to listOf("trademark"),
        "©️" to listOf("copyright"),
        "®️" to listOf("registered"),
        "👁️‍🗨️" to listOf("eye", "speech", "bubble"),
        "🔚" to listOf("end"),
        "🔙" to listOf("back"),
        "🔛" to listOf("on", "arrow"),
        "🔝" to listOf("top"),
        "🔜" to listOf("soon"),
        "〰️" to listOf("wavy", "dash"),
        "➰" to listOf("curly", "loop"),
        "➿" to listOf("double", "loop"),
        "✔️" to listOf("check", "mark"),
        "☑️" to listOf("checked", "box"),
        "🔘" to listOf("radio", "button"),
        "🔴" to listOf("red", "circle"),
        "🟠" to listOf("orange", "circle"),
        "🟡" to listOf("yellow", "circle"),
        "🟢" to listOf("green", "circle"),
        "🔵" to listOf("blue", "circle"),
        "🟣" to listOf("purple", "circle"),
        "⚫" to listOf("black", "circle"),
        "⚪" to listOf("white", "circle"),
        "🟤" to listOf("brown", "circle"),
        "🔺" to listOf("red", "triangle", "up"),
        "🔻" to listOf("red", "triangle", "down"),
        "🔸" to listOf("orange", "diamond", "small"),
        "🔹" to listOf("blue", "diamond", "small"),
        "🔶" to listOf("orange", "diamond"),
        "🔷" to listOf("blue", "diamond"),
        "🔳" to listOf("white", "square", "button"),
        "🔲" to listOf("black", "square", "button"),
        "🟥" to listOf("red", "square"),
        "🟧" to listOf("orange", "square"),
        "🟨" to listOf("yellow", "square"),
        "🟩" to listOf("green", "square"),
        "🟦" to listOf("blue", "square"),
        "🟪" to listOf("purple", "square"),
        "⬛" to listOf("black", "square"),
        "⬜" to listOf("white", "square"),
        "🟫" to listOf("brown", "square"),
        "📣" to listOf("megaphone"),
        "📢" to listOf("loudspeaker"),
        "🗨️" to listOf("speech", "balloon"),
        "🗯️" to listOf("angry", "balloon"),
        "💭" to listOf("thought", "balloon"),
        "💬" to listOf("speech", "bubble"),

        // ---------------- Flags ----------------
        "🏁" to listOf("checkered", "flag", "race"),
        "🚩" to listOf("triangular", "flag"),
        "🎌" to listOf("crossed", "flags", "japan"),
        "🏴" to listOf("black", "flag"),
        "🏳️" to listOf("white", "flag"),
        "🏳️‍🌈" to listOf("rainbow", "flag", "pride", "lgbt"),
        "🏳️‍⚧️" to listOf("transgender", "flag"),
        "🏴‍☠️" to listOf("pirate", "flag"),
        "🇦🇩" to listOf("andorra"),
        "🇦🇪" to listOf("united", "arab", "emirates", "uae"),
        "🇦🇫" to listOf("afghanistan"),
        "🇦🇬" to listOf("antigua", "barbuda"),
        "🇦🇮" to listOf("anguilla"),
        "🇦🇱" to listOf("albania"),
        "🇦🇲" to listOf("armenia"),
        "🇦🇴" to listOf("angola"),
        "🇦🇶" to listOf("antarctica"),
        "🇦🇷" to listOf("argentina"),
        "🇦🇸" to listOf("american", "samoa"),
        "🇦🇹" to listOf("austria"),
        "🇦🇺" to listOf("australia"),
        "🇦🇼" to listOf("aruba"),
        "🇦🇽" to listOf("aland", "islands"),
        "🇦🇿" to listOf("azerbaijan"),
        "🇧🇦" to listOf("bosnia", "herzegovina"),
        "🇧🇧" to listOf("barbados"),
        "🇧🇩" to listOf("bangladesh"),
        "🇧🇪" to listOf("belgium"),
        "🇧🇫" to listOf("burkina", "faso"),
        "🇧🇬" to listOf("bulgaria"),
        "🇧🇭" to listOf("bahrain"),
        "🇧🇮" to listOf("burundi"),
        "🇧🇯" to listOf("benin"),
        "🇧🇲" to listOf("bermuda"),
        "🇧🇳" to listOf("brunei"),
        "🇧🇴" to listOf("bolivia"),
        "🇧🇷" to listOf("brazil"),
        "🇧🇸" to listOf("bahamas"),
        "🇧🇹" to listOf("bhutan"),
        "🇧🇼" to listOf("botswana"),
        "🇧🇾" to listOf("belarus"),
        "🇧🇿" to listOf("belize"),
        "🇨🇦" to listOf("canada"),
        "🇨🇩" to listOf("congo", "drc"),
        "🇨🇫" to listOf("central", "african", "republic"),
        "🇨🇬" to listOf("congo"),
        "🇨🇭" to listOf("switzerland", "swiss"),
        "🇨🇮" to listOf("cote", "ivoire", "ivory", "coast"),
        "🇨🇱" to listOf("chile"),
        "🇨🇲" to listOf("cameroon"),
        "🇨🇳" to listOf("china", "chinese"),
        "🇨🇴" to listOf("colombia"),
        "🇨🇷" to listOf("costa", "rica"),
        "🇨🇺" to listOf("cuba"),
        "🇨🇻" to listOf("cape", "verde"),
        "🇨🇾" to listOf("cyprus"),
        "🇨🇿" to listOf("czechia", "czech"),
        "🇩🇪" to listOf("germany", "deutsch", "german"),
        "🇩🇯" to listOf("djibouti"),
        "🇩🇰" to listOf("denmark", "danish"),
        "🇩🇲" to listOf("dominica"),
        "🇩🇴" to listOf("dominican", "republic"),
        "🇩🇿" to listOf("algeria"),
        "🇪🇨" to listOf("ecuador"),
        "🇪🇪" to listOf("estonia"),
        "🇪🇬" to listOf("egypt"),
        "🇪🇷" to listOf("eritrea"),
        "🇪🇸" to listOf("spain", "spanish"),
        "🇪🇹" to listOf("ethiopia"),
        "🇪🇺" to listOf("european", "union", "eu"),
        "🇫🇮" to listOf("finland", "finnish"),
        "🇫🇯" to listOf("fiji"),
        "🇫🇷" to listOf("france", "french"),
        "🇬🇦" to listOf("gabon"),
        "🇬🇧" to listOf("united", "kingdom", "uk", "britain"),
        "🇬🇩" to listOf("grenada"),
        "🇬🇪" to listOf("georgia"),
        "🇬🇭" to listOf("ghana"),
        "🇬🇮" to listOf("gibraltar"),
        "🇬🇱" to listOf("greenland"),
        "🇬🇲" to listOf("gambia"),
        "🇬🇳" to listOf("guinea"),
        "🇬🇷" to listOf("greece", "greek"),
        "🇬🇹" to listOf("guatemala"),
        "🇬🇺" to listOf("guam"),
        "🇬🇼" to listOf("guinea", "bissau"),
        "🇬🇾" to listOf("guyana"),
        "🇭🇰" to listOf("hong", "kong"),
        "🇭🇳" to listOf("honduras"),
        "🇭🇷" to listOf("croatia"),
        "🇭🇹" to listOf("haiti"),
        "🇭🇺" to listOf("hungary", "magyar"),
        "🇮🇩" to listOf("indonesia"),
        "🇮🇪" to listOf("ireland", "irish"),
        "🇮🇱" to listOf("israel"),
        "🇮🇲" to listOf("isle", "man"),
        "🇮🇳" to listOf("india"),
        "🇮🇶" to listOf("iraq"),
        "🇮🇷" to listOf("iran"),
        "🇮🇸" to listOf("iceland"),
        "🇮🇹" to listOf("italy", "italian"),
        "🇯🇲" to listOf("jamaica"),
        "🇯🇴" to listOf("jordan"),
        "🇯🇵" to listOf("japan", "japanese"),
        "🇰🇪" to listOf("kenya"),
        "🇰🇬" to listOf("kyrgyzstan"),
        "🇰🇭" to listOf("cambodia"),
        "🇰🇮" to listOf("kiribati"),
        "🇰🇲" to listOf("comoros"),
        "🇰🇳" to listOf("st", "kitts", "nevis"),
        "🇰🇵" to listOf("north", "korea"),
        "🇰🇷" to listOf("south", "korea"),
        "🇰🇼" to listOf("kuwait"),
        "🇰🇿" to listOf("kazakhstan"),
        "🇱🇦" to listOf("laos"),
        "🇱🇧" to listOf("lebanon"),
        "🇱🇨" to listOf("st", "lucia"),
        "🇱🇮" to listOf("liechtenstein"),
        "🇱🇰" to listOf("sri", "lanka"),
        "🇱🇷" to listOf("liberia"),
        "🇱🇸" to listOf("lesotho"),
        "🇱🇹" to listOf("lithuania"),
        "🇱🇺" to listOf("luxembourg"),
        "🇱🇻" to listOf("latvia"),
        "🇱🇾" to listOf("libya"),
        "🇲🇦" to listOf("morocco"),
        "🇲🇨" to listOf("monaco"),
        "🇲🇩" to listOf("moldova"),
        "🇲🇪" to listOf("montenegro"),
        "🇲🇬" to listOf("madagascar"),
        "🇲🇭" to listOf("marshall", "islands"),
        "🇲🇰" to listOf("north", "macedonia"),
        "🇲🇱" to listOf("mali"),
        "🇲🇲" to listOf("myanmar", "burma"),
        "🇲🇳" to listOf("mongolia"),
        "🇲🇴" to listOf("macao"),
        "🇲🇷" to listOf("mauritania"),
        "🇲🇹" to listOf("malta"),
        "🇲🇺" to listOf("mauritius"),
        "🇲🇻" to listOf("maldives"),
        "🇲🇼" to listOf("malawi"),
        "🇲🇽" to listOf("mexico", "mexican"),
        "🇲🇾" to listOf("malaysia"),
        "🇲🇿" to listOf("mozambique"),
        "🇳🇦" to listOf("namibia"),
        "🇳🇪" to listOf("niger"),
        "🇳🇬" to listOf("nigeria"),
        "🇳🇮" to listOf("nicaragua"),
        "🇳🇱" to listOf("netherlands", "dutch", "holland"),
        "🇳🇴" to listOf("norway", "norwegian"),
        "🇳🇵" to listOf("nepal"),
        "🇳🇿" to listOf("new", "zealand"),
        "🇴🇲" to listOf("oman"),
        "🇵🇦" to listOf("panama"),
        "🇵🇪" to listOf("peru"),
        "🇵🇬" to listOf("papua", "new", "guinea"),
        "🇵🇭" to listOf("philippines"),
        "🇵🇰" to listOf("pakistan"),
        "🇵🇱" to listOf("poland", "polish"),
        "🇵🇷" to listOf("puerto", "rico"),
        "🇵🇸" to listOf("palestine"),
        "🇵🇹" to listOf("portugal", "portuguese"),
        "🇵🇾" to listOf("paraguay"),
        "🇶🇦" to listOf("qatar"),
        "🇷🇴" to listOf("romania", "romanian"),
        "🇷🇸" to listOf("serbia"),
        "🇷🇺" to listOf("russia", "russian"),
        "🇷🇼" to listOf("rwanda"),
        "🇸🇦" to listOf("saudi", "arabia"),
        "🇸🇧" to listOf("solomon", "islands"),
        "🇸🇨" to listOf("seychelles"),
        "🇸🇩" to listOf("sudan"),
        "🇸🇪" to listOf("sweden", "swedish"),
        "🇸🇬" to listOf("singapore"),
        "🇸🇮" to listOf("slovenia"),
        "🇸🇰" to listOf("slovakia"),
        "🇸🇱" to listOf("sierra", "leone"),
        "🇸🇲" to listOf("san", "marino"),
        "🇸🇳" to listOf("senegal"),
        "🇸🇴" to listOf("somalia"),
        "🇸🇷" to listOf("suriname"),
        "🇸🇸" to listOf("south", "sudan"),
        "🇸🇻" to listOf("el", "salvador"),
        "🇸🇾" to listOf("syria"),
        "🇸🇿" to listOf("eswatini", "swaziland"),
        "🇹🇩" to listOf("chad"),
        "🇹🇬" to listOf("togo"),
        "🇹🇭" to listOf("thailand"),
        "🇹🇯" to listOf("tajikistan"),
        "🇹🇱" to listOf("timor", "leste"),
        "🇹🇲" to listOf("turkmenistan"),
        "🇹🇳" to listOf("tunisia"),
        "🇹🇴" to listOf("tonga"),
        "🇹🇷" to listOf("turkey", "turkiye"),
        "🇹🇹" to listOf("trinidad", "tobago"),
        "🇹🇼" to listOf("taiwan"),
        "🇹🇿" to listOf("tanzania"),
        "🇺🇦" to listOf("ukraine"),
        "🇺🇬" to listOf("uganda"),
        "🇺🇸" to listOf("united", "states", "usa", "america"),
        "🇺🇾" to listOf("uruguay"),
        "🇺🇿" to listOf("uzbekistan"),
        "🇻🇦" to listOf("vatican"),
        "🇻🇪" to listOf("venezuela"),
        "🇻🇳" to listOf("vietnam"),
        "🇾🇪" to listOf("yemen"),
        "🇿🇦" to listOf("south", "africa"),
        "🇿🇲" to listOf("zambia"),
        "🇿🇼" to listOf("zimbabwe"),
        "🏴󠁧󠁢󠁥󠁮󠁧󠁿" to listOf("england", "english"),
        "🏴󠁧󠁢󠁳󠁣󠁴󠁿" to listOf("scotland", "scottish"),
        "🏴󠁧󠁢󠁷󠁬󠁳󠁿" to listOf("wales", "welsh")
    )
}
